/**
 * Pre-Infrastructure Install — Site Discovery Checklist (v1).
 *
 * Mirrors the 28-tab Pre-Install_Site_Discovery_Checklist.xlsx. Keys are
 * part of the stored data — never rename a key once projects exist; add
 * new ones instead.
 */
import type { FieldDef, FieldType, SectionDef, TableDef, TemplateDef } from "./types";

export const CONDITION = ["Excellent", "Good", "Fair", "Poor", "End-of-life"];
export const KEEP_REPLACE = ["Keep", "Reuse-reconfig", "Replace", "Decommission", "Needs-eval"];
export const PRIORITY = ["Critical", "Standard", "Nice-to-have"];
export const RISK = ["Low", "Medium", "High", "Blocker"];
export const YN = ["Yes", "No", "Unknown"];

function q(
  key: string,
  label: string,
  type: FieldType = "text",
  more: Partial<FieldDef> = {},
): FieldDef {
  return { key, label, type, ...more };
}

const yn = (key: string, label: string, hint?: string, more: Partial<FieldDef> = {}) =>
  q(key, label, "yn", { hint, ...more });
const txt = (key: string, label: string, hint?: string, more: Partial<FieldDef> = {}) =>
  q(key, label, "text", { hint, ...more });
const num = (key: string, label: string, hint?: string, more: Partial<FieldDef> = {}) =>
  q(key, label, "number", { hint, ...more });
const pick = (key: string, label: string, options: string[], hint?: string) =>
  q(key, label, "choice", { options, hint });
const multi = (key: string, label: string, options: string[], hint?: string) =>
  q(key, label, "multi", { options, hint });
const shot = (key: string, label: string, hint?: string) =>
  q(key, label, "photo", { hint, photo: "required" });

const keepCol = q("keep", "Keep / replace", "choice", { options: KEEP_REPLACE });
const notesCol = q("notes", "Notes", "textarea");

/* ------------------------------------------------------------------------ */

const cover: SectionDef = {
  key: "cover",
  number: 0,
  title: "Site & walkthrough team",
  short: "Site",
  icon: "building",
  intro:
    "Walk the site BEFORE committing to a rip-and-replace. The goal: the install team can produce a complete scope, BOM and labor estimate without a second visit. Mark N/A rather than leaving anything blank.",
  blocks: [
    {
      kind: "fields",
      title: "Site identification",
      fields: [
        txt("client_name", "Client / company name"),
        txt("site_name", "Site name / nickname", undefined, { placeholder: "e.g. Riverside Main" }),
        txt("street", "Street address"),
        txt("city_state_zip", "City / State / Zip"),
        multi("site_type", "Site type", ["Office", "Warehouse", "Medical", "Retail", "Mixed", "Industrial"]),
        num("sqft", "Approx square footage", undefined, { unit: "sq ft" }),
        num("floors", "Number of floors"),
        num("year_built", "Year building constructed", "Pre-1980 → flag asbestos / lead paint"),
        pick("ownership", "Building ownership", ["Owned", "Leased"]),
        q("landlord", "Landlord / property manager", "contact", {
          hint: "Needed for ceiling and conduit work approvals",
        }),
        num("headcount_peak", "Employee headcount on-site (peak)"),
        num("headcount_avg", "Employee headcount on-site (avg)"),
        num("headcount_12mo", "Projected headcount in 12 months"),
        txt("hours", "Operating hours / shift pattern", "Drives after-hours cutover windows"),
        multi("work_windows", "Permissible work windows", ["Business hours", "Nights", "Weekends", "24x7"]),
      ],
    },
    {
      kind: "fields",
      title: "Walkthrough team",
      fields: [
        q("lead_walker", "Lead walker", "contact"),
        q("secondary_walker", "Secondary walker", "contact"),
        q("client_sponsor", "Client sponsor", "contact"),
        q("facility_poc", "Facility POC", "contact"),
        q("lowvolt_vendor", "Low-volt vendor contact", "contact"),
        q("alarm_poc", "Alarm / monitoring POC", "contact"),
        q("building_super", "Building super / landlord POC", "contact"),
      ],
    },
    {
      kind: "fields",
      title: "What to bring",
      fields: [
        q("bring", "Kit check", "checklist", {
          photo: "none",
          items: [
            "Flashlight + headlamp (ceiling + closet work)",
            "Ladder access OR plan to coordinate client ladder",
            "Measuring tape (25'+) and laser measure",
            "Phone charged (this app works offline)",
            "Cable toner / tracer (for unlabeled runs)",
            "Multimeter",
            "USB → RJ45 adapter + patch cables for live-port speed test",
            "Credentials for client wifi (if available)",
            "Business cards / NDAs if needed",
          ],
        }),
      ],
    },
  ],
};

const facility: SectionDef = {
  key: "facility",
  number: 1,
  title: "Facility & pathways",
  short: "Facility",
  icon: "layers",
  intro:
    "The single largest install cost driver after labor. For every space where new wire will be pulled or recovered, document the ceiling, access, hazards and firestop requirements.",
  blocks: [
    {
      kind: "table",
      table: {
        key: "spaces",
        title: "Spaces",
        singular: "Space",
        columns: [
          txt("space", "Space / room"),
          pick("ceiling", "Ceiling type", ["Drop / ACT", "Hard lid", "Open deck", "Plenum return", "Mixed"]),
          pick("access", "Access level", ["Easy", "Ladder", "Lift required", "Restricted"]),
          num("deck_ft", "Deck height", undefined, { unit: "ft" }),
          q("observations", "Observations / hazards", "textarea"),
        ],
        titleKeys: ["space"],
        subtitleKeys: ["ceiling", "deck_ft"],
        presets: [
          "Front lobby / reception",
          "Open bullpen",
          "Private offices wing",
          "Conference room",
          "Training room",
          "Break room / kitchen",
          "Copy / print room",
          "IT closet (MDF)",
          "IT closet (IDF)",
          "Server / data room",
          "Warehouse / shop floor",
          "Mezzanine",
          "Catwalks",
          "Loading dock",
          "Garage / fleet area",
          "Hallways / corridors",
          "Exterior / courtyard",
          "Rooftop / mech penthouse",
          "Elevator machine room",
        ],
      },
    },
    {
      kind: "fields",
      title: "Pathway inventory",
      fields: [
        yn("tray", "Existing cable tray / J-hook paths above ceiling", "Size, fill, free capacity", { extras: ["qty", "risk"] }),
        yn("riser", "Backbone riser / sleeves between floors", "Count, size, sealed/firestopped", { extras: ["qty", "risk"] }),
        yn("conduit_int", "Conduit (interior)", "EMT size, fill, existing pull strings", { extras: ["qty", "risk"] }),
        yn("conduit_ext", "Conduit (exterior / underground)", "Document demarc runs", { extras: ["qty", "risk"] }),
        pick("plenum", "Plenum vs non-plenum ceiling space", ["Plenum", "Non-plenum", "Mixed", "Unknown"], "Dictates jacket rating"),
        yn("firestop", "Firestop penetrations required (walls/floors)", "Count by rating / location", { extras: ["qty", "risk"] }),
        yn("core_floor", "Core drilling needed (floors)", "Count + diameters", { extras: ["qty", "risk"] }),
        yn("core_wall", "Core drilling needed (walls)", undefined, { extras: ["qty", "risk"] }),
        pick("backbone_pref", "Fiber vs copper backbone preference", ["Fiber", "Copper", "Mixed", "Undecided"]),
        yn("grounding", "Grounding / bonding path (TMGB/TGB)", undefined, { extras: ["risk"] }),
        yn("asbestos", "Asbestos / lead paint concerns in ceiling", "Flag any pre-1980 construction", { extras: ["risk"] }),
        yn("hazmat", "Hazmat / biohazard restrictions in any area", undefined, { extras: ["risk"] }),
        yn("historic", "Historical / landmark restrictions", "Impacts surface mount, visible pathways", { extras: ["risk"] }),
        yn("wet", "Wet / high-humidity areas", "Drives jacket and enclosure choice", { extras: ["risk"] }),
        yn("class1", "Explosion-proof / Class 1 Div areas", "Fuel, chemistry, grain", { extras: ["risk"] }),
        yn("union", "Union / prevailing wage labor required", undefined, { extras: ["risk"] }),
        yn("escort", "Building security / escort required for techs", undefined, { extras: ["risk"] }),
        q("after_hours", "After-hours access process", "textarea", { hint: "Keys, codes, security guard" }),
      ],
    },
  ],
};

const mdf: SectionDef = {
  key: "mdf",
  number: 2,
  title: "MDF & server room",
  short: "MDF",
  icon: "server",
  intro:
    "Every physical and environmental property of the space that will house core gear. Photos: rack front, rack back, overhead cabling, floor, power, cooling, and equipment labels.",
  blocks: [
    {
      kind: "fields",
      fields: [
        txt("location", "Location (floor / room number)"),
        pick("dedicated", "Dedicated room or shared closet?", ["Dedicated room", "Shared closet", "Open area"]),
        txt("dimensions", "Room dimensions (L × W × ceiling H)"),
        txt("door", "Door type / width / lock", "Will a new rack fit through?"),
        txt("floor", "Floor type", "Raised floor? Static-dissipative? Tile condition"),
        num("racks_2post", "Rack count — 2-post"),
        num("racks_4post", "Rack count — 4-post / enclosed cabinet"),
        num("rack_u", "Rack height each", undefined, { unit: "U" }),
        txt("rack_dims", "Rack depth / width"),
        pick("rack_condition", "Rack condition / grounding bonded", ["Good + bonded", "Good, not bonded", "Poor", "Unknown"]),
        num("wall_cabinets", "Wall-mount cabinets"),
        num("free_u", "Available free rack U (contiguous)", undefined, { unit: "U" }),
        pick("cable_mgmt", "Cable management", ["Vertical + horizontal", "Horizontal only", "Vertical only", "None"]),
        txt("patch_panels", "Patch panels (count × ports × rating)"),
        q("labeling", "Labeling scheme on existing panels / cables", "textarea"),
        yn("ladder_rack", "Ladder rack / overhead tray in-room"),
        yn("underfloor", "Floor-penetration / underfloor pathway"),
        txt("hvac", "Dedicated HVAC? BTU rating", "Portable AC is a red flag", { extras: ["risk"] }),
        txt("temp_today", "Temperature / humidity today", "Record the reading"),
        yn("temp_monitoring", "Temp / humidity monitoring in place"),
        yn("leak_sensor", "Water / leak sensor"),
        pick("suppression", "Fire suppression type", ["Dry pipe", "Pre-action", "Wet sprinkler", "FM-200", "Novec", "None", "Unknown"]),
        yn("smoke", "Smoke detection present"),
        txt("circuits", "Dedicated power circuits — count × amps × V"),
        txt("breaker_panel", "Dedicated breaker panel location"),
        txt("ups", "UPS — make / model / kVA / battery age", undefined, { extras: ["condition"] }),
        txt("ups_runtime", "UPS runtime at current load", undefined, { unit: "min" }),
        pick("pdu", "PDU type", ["Metered", "Switched", "Basic", "None"]),
        pick("generator", "Generator-backed? ATS present", ["Generator + ATS", "Generator, manual", "No generator", "Unknown"]),
        yn("tmgb", "Grounding bar (TMGB) present and bonded"),
        pick("room_access", "Access control to room", ["Door reader", "Keyed", "Combination", "Nothing"]),
        pick("housekeeping", "Housekeeping", ["Clean", "Cluttered", "Storage dumping ground"]),
        yn("overhead_water", "Overhead water pipes or sprinklers over racks", "Big risk flag", { extras: ["risk"] }),
        yn("combustibles", "Combustibles stored in room", undefined, { extras: ["risk"] }),
        yn("paging_gear", "Phone / overhead paging gear present"),
        yn("alarm_panel", "Burglar / fire alarm panel in room"),
        yn("nvr_present", "Camera / NVR present"),
        pick("lighting", "Lighting / emergency lighting", ["Good", "Adequate", "Poor", "No emergency lighting"]),
        q("expansion", "Expansion space available (future growth)", "textarea"),
      ],
    },
  ],
};

const idf: SectionDef = {
  key: "idf",
  number: 3,
  title: "Wiring closets (IDF)",
  short: "IDFs",
  icon: "network",
  intro:
    "IDFs are the secondary wiring closets a site needs when one MDF can't reach every jack within 100 m / 328 ft. Each holds patch panels + access switches and uplinks to the MDF. If the whole site runs from the MDF, mark this section N/A. Distance to MDF decides copper (<300 ft) vs fiber.",
  blocks: [
    {
      kind: "table",
      table: {
        key: "idfs",
        title: "Closets",
        singular: "IDF",
        columns: [
          txt("name", "Closet name / room number"),
          txt("floor", "Floor"),
          txt("dimensions", "Dimensions (L×W×H)"),
          txt("rack", "Rack type / size (U)"),
          num("free_u", "Free rack U", undefined, { unit: "U" }),
          txt("switch_count", "Access switch count"),
          txt("circuit", "Dedicated circuit (A)"),
          txt("ups", "UPS present"),
          txt("cooling", "Cooling source"),
          txt("uplink", "Uplink to MDF (media / distance ft)"),
          q("observations", "Observations", "textarea"),
        ],
        titleKeys: ["name"],
        subtitleKeys: ["floor", "uplink"],
        example: {
          name: "IDF-1 · Rm 214",
          floor: "2nd",
          dimensions: "3' × 3' × 9'",
          rack: "Wall cabinet 12U",
          free_u: "4",
          switch_count: "1 (24-port stack)",
          circuit: "1 × 20A",
          ups: "Yes — 1500VA, 2 yr old",
          cooling: "Ambient from hallway (flag)",
          uplink: "Fiber LC-LC OM4, ~180 ft via tray",
          observations: "Keyed lock; chemicals on floor — move before cutover",
        },
      },
    },
  ],
};

const wan: SectionDef = {
  key: "wan",
  number: 4,
  title: "WAN & ISP",
  short: "WAN",
  icon: "globe",
  intro:
    "Document BOTH current circuits and any contractual commitments the client is locked into. Include public IPs — needed for the firewall rebuild.",
  blocks: [
    {
      kind: "fields",
      title: "Primary circuit",
      fields: [
        txt("p_carrier", "Primary carrier"),
        pick("p_type", "Primary circuit type", ["Fiber dedicated", "Cable", "DSL", "Fixed-wireless", "LTE/5G"]),
        txt("p_bandwidth", "Bandwidth (down / up)"),
        txt("p_sla", "SLA (uptime, MTTR)"),
        txt("p_ips", "Static IPs (count + range)"),
        num("p_cost", "Monthly cost", undefined, { unit: "$" }),
        q("p_contract_end", "Contract end date", "date"),
        txt("p_account", "Account number / circuit ID"),
        txt("p_demarc", "Demarc location", "Take a photo of the demarc", { photo: "required" }),
        pick("p_handoff", "Handoff type", ["RJ45 copper", "SMF", "MMF", "SFP", "SFP+"]),
      ],
    },
    {
      kind: "fields",
      title: "Secondary & services",
      fields: [
        txt("s_carrier", "Secondary carrier"),
        txt("s_type", "Secondary circuit type / speed"),
        txt("s_demarc", "Secondary demarc + handoff"),
        pick("failover", "Failover method today", ["SD-WAN", "Dual-WAN FW", "Manual", "None"]),
        txt("utilization", "Current WAN utilization (peak)", "Pull 30-day graph from carrier portal"),
        txt("dns_registrar", "Public DNS registrar / host"),
        pick("email_tenant", "Email tenant", ["M365", "Google Workspace", "On-prem Exchange", "Other"]),
        txt("mx", "MX records point to"),
        yn("ptr", "Reverse DNS / PTR records configured"),
        txt("smtp_relays", "External SMTP relays in use"),
        txt("s2s_vpn", "Site-to-site VPN tunnels (count + peers)"),
        txt("ra_vpn", "Remote access VPN platform", "Client count, auth method"),
        txt("sip_carrier", "SIP trunk carrier (if separate from PBX)"),
        txt("mpls", "Dedicated MPLS or SD-WAN overlay"),
        yn("loa", "Carrier LOA / CFA required for new circuit"),
        txt("cutover_window", "Cutover coordination window with carrier"),
      ],
    },
  ],
};

const firewall: SectionDef = {
  key: "firewall",
  number: 5,
  title: "Firewall & core",
  short: "Firewall",
  icon: "shield",
  blocks: [
    {
      kind: "fields",
      title: "Edge firewall",
      fields: [
        txt("fw_model", "Firewall make / model", undefined, { extras: ["condition"] }),
        txt("fw_firmware", "OS / firmware version"),
        q("fw_support_end", "Support contract end date", "date"),
        txt("fw_ha", "HA pair? passive device"),
        txt("fw_throughput", "Throughput today / headroom"),
        multi("fw_licensing", "Advanced licensing enabled", ["IPS", "URL filter", "AV", "Sandboxing", "DNS filter", "None"]),
        num("fw_rules", "Rule count (approx)"),
        txt("fw_vlans", "VLAN count + L3 interfaces"),
        multi("fw_routing", "Routing protocol in use", ["Static only", "OSPF", "BGP", "Other"]),
        pick("dhcp", "DHCP served by", ["Firewall", "Windows server", "Core switch", "Other"]),
        txt("dns_fwd", "DNS forwarders configured"),
        yn("ssl_inspect", "SSL/TLS inspection in use?"),
        yn("captive", "Captive portal / guest Wi-Fi NAC"),
        txt("logging", "Logging / SIEM destination"),
        yn("fw_backup", "Firewall config backed up / rotation"),
      ],
    },
    {
      kind: "fields",
      title: "Core switching",
      fields: [
        txt("core_model", "Core switch make / model", undefined, { extras: ["condition"] }),
        pick("core_stack", "Stacked / standalone", ["Stacked", "Standalone", "Chassis"]),
        txt("core_uplink", "Uplink to firewall — speed / media"),
        num("core_poe", "Core switch PoE budget", undefined, { unit: "W" }),
        txt("stp", "Spanning tree mode / root bridge"),
        yn("qos", "QoS / voice VLAN configured"),
        yn("l2_loops", "Layer-2 loops observed / errdisable ports", undefined, { extras: ["risk"] }),
        yn("guest_isolation", "Guest network isolation enforced"),
        txt("internal_ca", "Internal certificate authority (AD CS, etc.)"),
      ],
    },
  ],
};

const switches: SectionDef = {
  key: "switches",
  number: 6,
  title: "Access switches",
  short: "Switches",
  icon: "toggle",
  intro:
    "One record per switch. Treat a stack as one logical device and note the unit count. Flag unmanaged consumer switches found in closets or at desks — they're normally removed on rip-and-replace.",
  blocks: [
    {
      kind: "table",
      table: {
        key: "access_switches",
        title: "Switches",
        singular: "Switch",
        columns: [
          txt("location", "Location / closet"),
          txt("make", "Make"),
          txt("model", "Model"),
          num("ports", "Port count"),
          txt("poe", "PoE class (AT/BT budget W)"),
          txt("uplink", "Uplink speed / media"),
          yn("managed", "Managed"),
          txt("firmware", "Firmware"),
          num("age", "Age", undefined, { unit: "yrs" }),
          keepCol,
          notesCol,
        ],
        titleKeys: ["make", "model"],
        subtitleKeys: ["location", "ports"],
      },
    },
  ],
};

const wireless: SectionDef = {
  key: "wireless",
  number: 7,
  title: "Wireless",
  short: "Wi-Fi",
  icon: "wifi",
  intro:
    "Walk every space with a Wi-Fi analyzer where possible. Note dead zones, interference and mounting constraints — surface locations that need extra APs, boom mounts or outdoor-rated gear.",
  blocks: [
    {
      kind: "table",
      table: {
        key: "aps",
        title: "Access points",
        singular: "AP",
        columns: [
          txt("location", "AP location / room"),
          txt("make", "Make"),
          txt("model", "Model"),
          num("mount_ft", "Mount height", undefined, { unit: "ft" }),
          pick("mount", "Mount type", ["Ceiling grid", "Hard ceiling", "Wall", "Boom", "Outdoor pole", "Above ceiling"]),
          txt("poe_source", "PoE source"),
          num("age", "Age", undefined, { unit: "yrs" }),
          keepCol,
          notesCol,
        ],
        titleKeys: ["location"],
        subtitleKeys: ["make", "model"],
      },
    },
    {
      kind: "fields",
      title: "Controller & SSIDs",
      fields: [
        pick("controller", "Controller / cloud platform", ["Meraki", "UniFi", "Mist", "ArubaOS", "Omada", "Ruckus", "Standalone", "Other"]),
        txt("controller_host", "Controller location / hosting"),
        q("mgmt_license_end", "Mgmt licensing end date", "date"),
        q("ssids", "SSIDs today (list)", "textarea"),
        multi("ssid_auth", "Auth methods in use", ["PSK", "802.1X", "Captive portal", "Open"]),
        txt("ssid_vlans", "VLAN per SSID"),
        txt("guest_cap", "Guest bandwidth cap"),
        txt("radius", "RADIUS / 802.1X infrastructure"),
        q("dead_zones", "Dead zones noted", "textarea"),
        txt("interference", "Known interference", "Microwave, radar, neighbors"),
        multi("outdoor", "Outdoor coverage requirements", ["Patio", "Yard", "Parking", "Docks", "None"]),
        yn("ptp", "Point-to-point bridges in use"),
        txt("byod", "BYOD policy / separation"),
        pick("backhaul", "Mesh / wired-backhaul mix", ["All wired", "Mostly wired", "Mostly mesh", "All mesh"]),
      ],
    },
  ],
};

const cabling: SectionDef = {
  key: "cabling",
  number: 8,
  title: "Cable plant & drops",
  short: "Cabling",
  icon: "cable",
  intro:
    "This drives most of the install BOM. Count every drop by purpose. Verify the labeling scheme end-to-end on at least five random drops.",
  blocks: [
    {
      kind: "fields",
      title: "Existing plant",
      fields: [
        multi("category", "Existing copper category", ["Cat5e", "Cat6", "Cat6a", "Cat7", "Mixed / unknown"], undefined),
        pick("condition", "Existing cable condition", CONDITION),
        pick("jacket", "Jacket type", ["Riser (CMR)", "Plenum (CMP)", "Mixed", "Unknown"]),
        pick("shielded", "Shielded or UTP", ["UTP", "Shielded", "Mixed"]),
        txt("jack_colors", "Faceplate / jack color scheme"),
        txt("panel_brand", "Patch panel brand"),
        txt("panel_ports", "Patch panel ports total / in use"),
        q("label_scheme", "Label scheme in use (describe)", "textarea"),
        yn("label_consistent", "Scheme consistent between panel and faceplate?"),
        yn("toned", "Verified with toner on sample drops (5+)"),
        yn("cert_data", "Testing data available (Fluke certs)"),
        txt("fiber_count", "Fiber in cable plant (SMF / MMF count)"),
        multi("fiber_conn", "Fiber connectors", ["LC", "SC", "ST", "MTP"]),
        txt("fiber_enclosures", "Fiber cassettes / enclosures"),
        q("aerial", "Aerial / direct-burial runs", "textarea"),
        yn("damaged", "Damaged / abandoned cable visible", undefined, { extras: ["risk"] }),
      ],
    },
    {
      kind: "fields",
      title: "New drop plan — count by purpose",
      intro: "Estimated count, average length and pathway complexity for each purpose.",
      fields: [
        ["ws_data", "Workstation data (default 2 per seat)"],
        ["ws_phone", "Workstation phone (if separate run)"],
        ["printer", "Printer / MFP"],
        ["ap", "Wireless AP (PoE)"],
        ["camera", "IP camera (PoE)"],
        ["access_ctl", "Access-control reader / door controller"],
        ["alarm", "Alarm panel / cellular"],
        ["clock", "Clock / time attendance"],
        ["paging", "Overhead paging zone"],
        ["conf_audio", "Overhead speaker / mic (conf room)"],
        ["signage", "TV / signage display"],
        ["conf_codec", "Conference room camera / codec"],
        ["lectern", "Lectern / podium"],
        ["reception", "Reception / kiosk"],
        ["floor_box_guest", "Guest-only floor box"],
        ["kitchen", "Kitchen / break room (vending, TV)"],
        ["scanner", "Warehouse scanner cradles"],
        ["dock", "Loading dock"],
        ["shop", "Garage / shop floor"],
        ["outdoor", "Outdoor camera / AP"],
        ["spare", "Spare drops per IDF for growth"],
        ["floor_box", "Floor box drops (specify room)"],
        ["fiber_uplinks", "Fiber uplink runs (count × length)"],
      ].map(([key, label]) =>
        num(`drop_${key}`, label, undefined, { extras: ["lengthFt", "complexity"] }),
      ),
    },
  ],
};

const workstations: SectionDef = {
  key: "workstations",
  number: 9,
  title: "Workstations",
  short: "Seats",
  icon: "laptop",
  intro:
    "One record per seat. Capture enough for (1) the refresh BOM, (2) persona-based imaging and licensing, (3) migration order and cutover planning. Under ‘Current issue’, note complaints that would recur on new gear.",
  blocks: [
    {
      kind: "table",
      table: {
        key: "workstations",
        title: "Seats",
        singular: "Seat",
        columns: [
          txt("user", "User name"),
          txt("role", "Role / dept"),
          txt("seat", "Seat location"),
          pick("device_type", "Device type", ["Desktop", "Laptop", "Mini PC", "Thin client", "All-in-one", "Mac"]),
          txt("make", "Make"),
          txt("model", "Model"),
          txt("serial", "Serial / asset tag"),
          num("age", "Age", undefined, { unit: "yrs" }),
          txt("os", "OS + version"),
          txt("cpu", "CPU"),
          num("ram", "RAM", undefined, { unit: "GB" }),
          txt("storage", "Storage (type / GB)"),
          pick("encryption", "Disk encryption", ["BitLocker on", "FileVault on", "Off", "Unknown"]),
          txt("monitors", "Monitors (qty × size, make)"),
          txt("dock", "Dock (make/model)"),
          txt("peripherals", "Peripherals (headset, cam, scanner, pad)"),
          txt("lob", "LOB software / specialty"),
          pick("access_level", "Access level", ["Standard", "Power user", "Local admin"]),
          txt("phone", "Phone ext / softphone"),
          pick("mobility", "Mobility", ["In-office daily", "Hybrid", "Remote", "Field"]),
          txt("issue", "Current issue?"),
          keepCol,
          notesCol,
        ],
        titleKeys: ["user", "seat"],
        subtitleKeys: ["make", "model", "os"],
        example: {
          user: "Sarah Nguyen",
          role: "Accounting",
          seat: "2F · Finance 203",
          make: "Dell",
          model: "Latitude 5540",
          serial: "SN: C7XK9H2",
          age: "3",
          os: "Win 11 Pro 23H2",
          cpu: "i5-1335U",
          ram: "16",
          storage: "SSD 512",
          monitors: "2 × 24\" Dell P2419H",
          dock: "Dell WD19",
          peripherals: "Logitech Zone wired HS · HP ScanJet 2500",
          lob: "Sage Intacct · Excel heavy",
          phone: "x4203 (Zoom Phone)",
          issue: "Dock port intermittent",
          notes: "Wants 27\" primary + 24\" portrait secondary",
        },
      },
    },
  ],
};

const printers: SectionDef = {
  key: "printers",
  number: 10,
  title: "Printers & MFPs",
  short: "Print",
  icon: "printer",
  blocks: [
    {
      kind: "table",
      table: {
        key: "printers",
        title: "Printers",
        singular: "Printer",
        columns: [
          txt("location", "Location"),
          txt("make", "Make"),
          txt("model", "Model"),
          pick("color", "Mono / color", ["Mono", "Color"]),
          multi("functions", "Functions", ["Print", "Copy", "Scan", "Fax"]),
          pick("ownership", "Lease vs own", ["Lease", "Own"]),
          txt("lease", "Lease vendor / end date"),
          num("volume", "Monthly volume", undefined, { unit: "pages" }),
          yn("fleet_agent", "Fleet-mgmt agent"),
          keepCol,
          notesCol,
        ],
        titleKeys: ["make", "model"],
        subtitleKeys: ["location", "color"],
      },
    },
    {
      kind: "fields",
      title: "Specialty print",
      fields: [
        txt("label_printers", "Label printers (Zebra, Dymo) — qty / model / location"),
        txt("receipt_printers", "Receipt printers (POS, kitchen) — qty / model"),
        txt("plotters", "Plotters / wide format — qty / model"),
        txt("badge_printers", "Badge printers (access control)"),
        txt("micr", "Check / MICR printers"),
        txt("fax", "Fax lines / eFax platform"),
        txt("scan_stations", "Scanning stations (production)"),
        txt("print_release", "Print release / badge-release system"),
        txt("papercut", "Pull-print / Equitrac / PaperCut"),
      ],
    },
  ],
};

const voice: SectionDef = {
  key: "voice",
  number: 11,
  title: "Phones & VoIP",
  short: "Voice",
  icon: "phone",
  blocks: [
    {
      kind: "fields",
      fields: [
        txt("pbx", "Current PBX make / model"),
        pick("hosting", "Hosted vs on-prem", ["Hosted / UCaaS", "On-prem", "Hybrid"]),
        txt("hosted_vendor", "Hosted vendor / contract end"),
        num("seats", "User / seat count"),
        txt("did", "DID range / main number"),
        txt("sip_carrier", "Carrier for SIP trunks"),
        txt("trunks", "Trunk count / concurrent call capacity"),
        num("pri_analog", "PRI / analog lines (count)"),
        txt("fax_lines", "Fax lines (count × purpose)"),
        yn("e911", "E911 location mapping in place?", undefined, { extras: ["risk"] }),
        txt("recording", "Call recording required / platform"),
        pick("ivr", "Auto-attendant / IVR complexity", ["None", "Simple", "Moderate", "Complex"]),
        num("hunt_groups", "Hunt groups / ring groups count"),
        yn("vm_email", "Voicemail-to-email in use"),
        num("softphone_users", "Softphone / mobile users count"),
        txt("headsets", "Headset standard (make/model)"),
        txt("conf_phones", "Conference phones (count × model × location)"),
        num("paging_zones", "Overhead paging zones"),
        yn("door_buzzer", "Door buzzer / entry phone integration"),
        yn("intercom", "Intercom / page-all from any handset"),
        yn("call_park", "Call park / shared line appearances"),
        txt("ata", "ATA / fax / specialty analog needs"),
        txt("legacy", "Legacy phones to retain (reason)"),
        yn("porting_loa", "Porting LOA already on file?"),
      ],
    },
  ],
};

const av: SectionDef = {
  key: "av",
  number: 12,
  title: "AV & conferencing",
  short: "AV",
  icon: "monitor",
  blocks: [
    {
      kind: "table",
      table: {
        key: "rooms",
        title: "Rooms",
        singular: "Room",
        columns: [
          txt("room", "Room name"),
          num("capacity", "Capacity", undefined, { unit: "seats" }),
          txt("display", "Display (make/model/size)"),
          txt("camera", "Camera"),
          txt("audio", "Mic / speaker"),
          txt("controller", "Room controller"),
          pick("uc", "UC platform", ["Teams", "Zoom", "Google Meet", "Webex", "BYOD", "None"]),
          keepCol,
          notesCol,
        ],
        titleKeys: ["room"],
        subtitleKeys: ["capacity", "uc"],
      },
    },
    {
      kind: "fields",
      title: "Signage, lobby, specialty displays",
      fields: [
        txt("lobby_display", "Lobby welcome / check-in display"),
        txt("menu_boards", "Digital menu boards / signage"),
        txt("wayfinding", "Wayfinding kiosks"),
        txt("kpi_dashboards", "Production / KPI dashboards (shop floor)"),
        txt("mass_notify", "Mass notification displays"),
        txt("paging_coverage", "Audio paging coverage (zones)"),
        txt("hearing_loop", "Hearing-loop / assistive listening"),
        txt("wireless_present", "Wireless presentation (ClickShare, AirPlay, Miracast)"),
        txt("whiteboards", "Interactive whiteboards"),
        txt("lectern", "Lectern / podium at specific rooms"),
      ],
    },
  ],
};

const servers: SectionDef = {
  key: "servers",
  number: 13,
  title: "Servers & compute",
  short: "Servers",
  icon: "database",
  intro:
    "One record per OS instance — including the 2008 VM nobody admits exists. Dependencies and app-owner are critical: orphaned app servers are the #1 cause of cutover failures. Mark cloud/SaaS instances so they aren't decommissioned by mistake.",
  blocks: [
    {
      kind: "table",
      table: {
        key: "servers",
        title: "Servers",
        singular: "Server",
        columns: [
          txt("hostname", "Hostname"),
          pick("kind", "Phys / VM", ["Physical", "VM", "Cloud"]),
          txt("host", "Hypervisor / host"),
          txt("rack_loc", "Rack / U location"),
          txt("make_model", "Make / model (physical)"),
          txt("serial", "Serial / asset"),
          txt("cpu", "CPU"),
          num("ram", "RAM", undefined, { unit: "GB" }),
          txt("storage", "Storage (type / GB)"),
          txt("mgmt_ip", "Mgmt IP"),
          txt("bmc", "iDRAC / iLO / BMC"),
          txt("os", "OS + version"),
          txt("role", "Role / purpose"),
          txt("services", "Services / ports listening"),
          txt("owner", "LOB app owner"),
          q("dependencies", "Dependencies (upstream / downstream)", "textarea"),
          txt("backup", "Backed up?"),
          txt("monitoring", "Monitoring agent"),
          txt("warranty", "Warranty / support end"),
          txt("downtime", "Downtime tolerance"),
          keepCol,
          notesCol,
        ],
        titleKeys: ["hostname"],
        subtitleKeys: ["kind", "os", "role"],
        example: {
          hostname: "SVR-APP01",
          host: "ESXi host CLUST-A",
          rack_loc: "Rack 1 · U18-19",
          make_model: "Dell PowerEdge R740 (host)",
          cpu: "4 vCPU",
          ram: "32",
          storage: "SSD 500 (thick)",
          mgmt_ip: "10.10.12.21",
          bmc: "iDRAC 10.10.90.21",
          os: "Win Server 2019 Std",
          role: "Sage Intacct middleware",
          services: "TCP 443, 1433 → SQL02",
          owner: "Finance — Lauren Stewart",
          dependencies: "Depends on SQL02; relied on by WEB01",
          backup: "Yes — Veeam nightly",
          monitoring: "Datto RMM + Veeam",
          warranty: "2027-04-18 (ProSupport)",
          downtime: "4h RTO",
        },
      },
    },
  ],
};

const storage: SectionDef = {
  key: "storage",
  number: 14,
  title: "Storage & backup",
  short: "Backup",
  icon: "hard-drive",
  blocks: [
    {
      kind: "fields",
      fields: [
        pick("platform", "Primary storage platform", ["SAN", "NAS", "DAS", "Cloud only", "None"]),
        txt("make_model", "Make / model"),
        txt("capacity", "Raw / usable capacity"),
        num("pct_used", "% used today", undefined, { unit: "%" }),
        multi("protocols", "Protocols in use", ["iSCSI", "FC", "NFS", "SMB"]),
        txt("snapshots", "Snapshot schedule / retention"),
        yn("replication", "Replication to secondary site"),
        txt("backup_sw", "Backup software (make / version)"),
        txt("backup_target", "Backup target (appliance / cloud)"),
        yn("immutable", "Immutable / air-gapped copy", undefined, { extras: ["risk"] }),
        txt("offsite", "Offsite retention"),
        q("restore_test", "Last successful full restore test", "date"),
        num("rpo", "RPO target", undefined, { unit: "hours" }),
        num("rto", "RTO target", undefined, { unit: "hours" }),
        yn("dr_runbook", "DR runbook exists"),
        num("cloud_tb", "Cloud backup consumption", undefined, { unit: "TB/mo" }),
        txt("shadow_it", "Shadow IT backups (Dropbox, personal drives)", undefined, { extras: ["risk"] }),
        txt("endpoint_backup", "Endpoint backup (CrashPlan, OneDrive KFM)"),
        txt("share_ratio", "File shares vs OneDrive/SharePoint ratio"),
      ],
    },
  ],
};

const identity: SectionDef = {
  key: "identity",
  number: 15,
  title: "Identity & core services",
  short: "Identity",
  icon: "key",
  blocks: [
    {
      kind: "fields",
      title: "Directory",
      fields: [
        txt("ad_domain", "On-prem AD domain name"),
        txt("functional_level", "Domain / forest functional level"),
        txt("dcs", "DC count / FSMO holders"),
        txt("entra_tenant", "Entra ID tenant"),
        pick("hybrid_sync", "Hybrid sync", ["Entra Connect", "Cloud Sync", "None", "Unknown"]),
        txt("sso", "SSO / SAML providers (list)"),
        num("mfa_pct", "Users with MFA", undefined, { unit: "%", extras: ["risk"] }),
        yn("conditional_access", "Conditional access policies in place"),
        num("priv_accounts", "Privileged accounts count"),
        txt("service_accounts", "Service accounts count / inventoried"),
        txt("gpo", "GPO count / complexity"),
        txt("gpo_filters", "GPO WMI / security filtering"),
      ],
    },
    {
      kind: "fields",
      title: "DNS, DHCP, PKI",
      fields: [
        txt("dns_internal", "DNS internal / split-brain config"),
        txt("dns_external", "DNS external hosting"),
        txt("dhcp", "DHCP server (role / scope count)"),
        txt("dhcp_options", "DHCP reservations / option 66 for VoIP"),
        txt("ca", "Internal CA / cert templates"),
      ],
    },
    {
      kind: "fields",
      title: "Email & endpoint",
      fields: [
        pick("email_tenant", "Email tenant", ["M365", "Google Workspace", "On-prem Exchange", "Other"]),
        txt("mailboxes", "Mailbox count / largest mailbox size"),
        num("shared_mailboxes", "Shared mailboxes count"),
        yn("public_folders", "Public folders in use"),
        yn("dmarc", "DMARC / SPF / DKIM aligned", undefined, { extras: ["risk"] }),
        txt("mdm", "MDM / Intune / Jamf posture"),
        txt("patching", "Endpoint patch tool"),
        txt("antimalware", "Endpoint anti-malware (make, deployment %)"),
        yn("edr", "EDR / XDR in place", undefined, { extras: ["risk"] }),
        txt("password_manager", "Password manager org tenant"),
        q("password_policy", "Password policy details", "textarea"),
      ],
    },
  ],
};

const apps: SectionDef = {
  key: "apps",
  number: 16,
  title: "LOB & SaaS apps",
  short: "Apps",
  icon: "app",
  blocks: [
    {
      kind: "table",
      table: {
        key: "apps",
        title: "Applications",
        singular: "App",
        columns: [
          txt("name", "App name"),
          txt("vendor", "Vendor"),
          pick("hosting", "Hosted / on-prem", ["SaaS", "On-prem", "Hybrid"]),
          num("users", "Users"),
          pick("criticality", "Criticality", ["Critical", "High", "Medium", "Low"]),
          txt("license", "License model"),
          txt("integrations", "Integrations / API"),
          keepCol,
          notesCol,
        ],
        titleKeys: ["name"],
        subtitleKeys: ["vendor", "criticality"],
      },
    },
  ],
};

const access: SectionDef = {
  key: "access",
  number: 17,
  title: "Access control",
  short: "Doors",
  icon: "door",
  intro:
    "Photo every door (both sides), every reader, strike/maglock, REX sensor, and the main panel — attach them on the Doors list below.",
  blocks: [
    {
      kind: "table",
      table: {
        key: "doors",
        title: "Doors",
        singular: "Door",
        columns: [
          txt("door", "Door / location"),
          pick("perimeter", "Perimeter / interior", ["Perimeter", "Interior"]),
          txt("reader", "Reader"),
          pick("lock", "Lock hardware", ["Electric strike", "Maglock", "Electrified mortise", "Delayed egress", "Mechanical only"]),
          yn("rex", "REX sensor"),
          yn("dps", "Door position sensor"),
          keepCol,
          notesCol,
        ],
        titleKeys: ["door"],
        subtitleKeys: ["perimeter", "lock"],
      },
    },
    {
      kind: "fields",
      title: "Platform",
      fields: [
        pick("platform", "Platform make / model", ["Avigilon Alta", "Brivo", "Verkada", "Genetec", "S2", "Lenel", "Keyscan", "Kantech", "Honeywell Pro-Watch", "Other"]),
        pick("hosting", "Hosted vs on-prem controller", ["Cloud", "On-prem", "Hybrid"]),
        txt("version", "Software version / support status"),
        num("doors_perimeter", "Door count (perimeter)"),
        num("doors_interior", "Door count (interior)"),
        yn("elevator", "Elevator floor control present"),
        yn("mantraps", "Mantraps / interlocks present"),
        multi("reader_tech", "Reader technology", ["Prox 125", "HID iCLASS", "MIFARE", "Mobile", "Multi-tech"]),
        multi("protocol", "Communication protocol", ["Wiegand", "OSDP", "OSDP SC"]),
        multi("credentials", "Credential types issued", ["Card", "Fob", "Mobile", "Biometric", "PIN"]),
        txt("visitor_mgmt", "Visitor management system"),
        yn("local_alarm", "Local alarm / strobe at breach doors"),
        yn("panel_battery", "Battery backup at panel"),
        yn("forced_alerts", "Door forced / held open alerting active"),
        yn("intrusion_integration", "Integration with intrusion alarm"),
        yn("camera_integration", "Integration with cameras"),
        yn("hr_integration", "Integration with HR for de-provisioning"),
        yn("key_hierarchy", "Override / mechanical key hierarchy documented"),
        txt("panic", "Panic / duress button locations"),
        txt("guard_tour", "Guard tour / patrol stations"),
        yn("lockdown", "Lockdown / shelter-in-place button"),
        txt("ada", "ADA / low-energy operators"),
        yn("credential_list", "Credential inventory list obtained"),
      ],
    },
  ],
};

const alarms: SectionDef = {
  key: "alarms",
  number: 18,
  title: "Intrusion alarm",
  short: "Alarm",
  icon: "siren",
  blocks: [
    {
      kind: "fields",
      fields: [
        pick("panel", "Panel make / model", ["DMP", "DSC", "Honeywell Vista", "Bosch", "Napco", "Qolsys", "Other"]),
        txt("monitoring_co", "Monitoring company"),
        txt("account", "Account number"),
        txt("ul_cert", "Monitoring certificate (UL / FM) if required"),
        multi("comm_path", "Communication path", ["Cellular", "IP", "Dual-path", "POTS"]),
        txt("keypads", "Keypad count / locations"),
        multi("zone_types", "Zone types present", ["Motion", "Door", "Glass break", "Duress", "Hold-up", "Smoke", "Water"]),
        num("zone_count", "Zone count"),
        txt("sirens", "Siren / strobe interior & exterior"),
        txt("battery", "Battery age / backup runtime", undefined, { extras: ["condition"] }),
        q("last_test", "Last successful test", "date"),
        q("false_alarms", "Open account items / known false alarms", "textarea"),
        txt("arming", "After-hours arming schedule / override"),
        yn("partitioned", "Partitioned (shared tenant / multiple areas)"),
        txt("integrations", "Integrations with access control / cameras"),
        txt("app", "Smartphone app / user mgmt platform"),
        yn("permit", "Permit / jurisdiction fees current"),
      ],
    },
  ],
};

const cameras: SectionDef = {
  key: "cameras",
  number: 19,
  title: "Cameras & NVR",
  short: "Cameras",
  icon: "cctv",
  blocks: [
    {
      kind: "table",
      table: {
        key: "cameras",
        title: "Cameras",
        singular: "Camera",
        columns: [
          txt("location", "Camera location"),
          pick("type", "Type", ["Dome", "Bullet", "Turret", "PTZ", "Fisheye", "Multi-sensor", "Doorbell"]),
          txt("make_model", "Make / model"),
          txt("resolution", "Resolution / lens"),
          txt("poe", "PoE class"),
          multi("ir_audio", "IR / audio", ["IR", "Audio"]),
          num("mount_ft", "Mount height", undefined, { unit: "ft" }),
          keepCol,
          notesCol,
        ],
        titleKeys: ["location"],
        subtitleKeys: ["type", "make_model"],
      },
    },
    {
      kind: "fields",
      title: "Recorder / platform",
      fields: [
        pick("recorder_type", "Recorder type", ["NVR", "Hybrid", "DVR", "Cloud-managed", "Cloud-only"]),
        pick("platform", "Make / platform", ["Milestone", "Avigilon", "Verkada", "Rhombus", "Eagle Eye", "Hikvision", "Dahua", "ExacqVision", "UniFi Protect", "Other"]),
        txt("storage", "Storage (TB) / retention days"),
        txt("raid", "RAID level / redundancy"),
        yn("cloud_archive", "Cloud archive / failover"),
        multi("analytics", "Video analytics in use", ["LPR", "Person/vehicle", "Loitering", "Line-cross", "AI search"]),
        txt("viewing", "Monitors / viewing stations (count × location)"),
        txt("mobile_app", "Mobile / web app in use by whom"),
        txt("export", "Export workflow for police / insurance"),
        yn("audio_consent", "Audio capture compliance", "Two-party consent states", { extras: ["risk"] }),
        yn("ac_integration", "Access control integration"),
        yn("forced_snapshot", "Door-forced snapshot flow"),
        yn("health", "Health monitoring / camera-down alerts"),
      ],
    },
  ],
};

const environmental: SectionDef = {
  key: "environmental",
  number: 20,
  title: "Environmental & safety",
  short: "Safety",
  icon: "flame",
  blocks: [
    {
      kind: "fields",
      fields: [
        txt("temp_sensors", "Temp sensors (location, platform)"),
        txt("humidity", "Humidity sensors"),
        txt("leak", "Water / leak sensors"),
        yn("smoke", "Smoke detection (interior)"),
        txt("fire_panel", "Fire alarm panel (make / monitoring)"),
        multi("suppression", "Suppression type by area", ["FM-200", "Novec 1230", "Pre-action", "Wet", "Dry chem"]),
        q("tank_inspection", "Suppression tank inspection date", "date"),
        yn("vesda", "Beam / aspirating smoke (data room)"),
        txt("generator", "Generator (make, kW, fuel, runtime)"),
        txt("ats", "ATS make / model"),
        q("gen_test", "Generator last test date", "date"),
        txt("fuel", "Fuel tank size / delivery contract"),
        yn("ups_env", "UPS environmental monitors"),
        yn("bms", "HVAC remote monitoring (BMS / BAS)"),
        txt("mass_notify", "Mass notification (Alertus, InformaCast)"),
        yn("noaa", "Weather radio / NOAA alerting"),
        txt("aed", "First aid / AED locations"),
        pick("egress_lighting", "Emergency lighting / exit signage", CONDITION),
        yn("surge", "Lightning protection / surge devices"),
      ],
    },
  ],
};

const lowvolt: SectionDef = {
  key: "lowvolt",
  number: 21,
  title: "Specialty low-volt",
  short: "Low-volt",
  icon: "zap",
  blocks: [
    {
      kind: "fields",
      fields: [
        txt("doorbell", "Video doorbell / entry camera"),
        txt("door_station", "Door station / intercom at each entry"),
        txt("intercom_platform", "Intercom platform (2N / Aiphone / Comelit)"),
        txt("paging", "Overhead paging zones + amp room"),
        txt("bgm", "Background music / white-noise masking"),
        txt("clocks", "Sync clocks (PoE/NTP) count & location"),
        txt("time_clocks", "Time attendance clocks / biometric"),
        txt("badge_printers", "Badge printers (visitor, employee)"),
        txt("kiosks", "Interactive wayfinding kiosks"),
        txt("occupancy", "Occupancy sensors / people counting"),
        txt("booking", "Space booking panels"),
        txt("nurse_call", "Nurse-call / staff-call"),
        txt("wander", "Patient wander / infant protection"),
        txt("bells", "Classroom bells / school scheduling"),
        txt("scoreboards", "Scoreboards / league timing"),
        txt("dock_levelers", "Loading-dock levelers / lights"),
        txt("scale_house", "Fuel-island / scale-house instrumentation"),
        txt("scada", "Industrial automation / PLC / SCADA", undefined, { extras: ["risk"] }),
        txt("ev", "EV charging stations (count / network)"),
        txt("solar", "Solar / battery monitoring interface"),
      ],
    },
  ],
};

const headcount: SectionDef = {
  key: "headcount",
  number: 22,
  title: "Headcount & growth",
  short: "Growth",
  icon: "users",
  blocks: [
    {
      kind: "table",
      table: {
        key: "departments",
        title: "Departments",
        singular: "Department",
        columns: [
          txt("department", "Department / team"),
          num("current", "Current headcount"),
          num("plus12", "+12 months"),
          num("plus24", "+24 months"),
          txt("persona", "Seat persona"),
          notesCol,
        ],
        titleKeys: ["department"],
        subtitleKeys: ["current", "persona"],
      },
    },
    {
      kind: "fields",
      title: "Workstyle mix",
      fields: [
        ["in_office", "Full-time in-office (per day avg)"],
        ["hybrid", "Hybrid (days/week in-office)"],
        ["remote", "Fully remote"],
        ["field", "Field / mobile only"],
        ["hot_desk", "Hot-desk / hotel seats"],
        ["shared", "Shared workstations (shift workers)"],
        ["visitors", "Visitors / contractors on-site daily"],
      ].map(([key, label]) => num(key, label, undefined, { extras: ["growth12"] })),
    },
  ],
};

const compliance: SectionDef = {
  key: "compliance",
  number: 23,
  title: "Compliance",
  short: "Compliance",
  icon: "scale",
  intro: "Regulatory posture that drives install requirements.",
  blocks: [
    {
      kind: "fields",
      fields: [
        ["hipaa", "HIPAA (PHI handled on site)"],
        ["pci", "PCI-DSS (card data processed on site)"],
        ["soc2", "SOC 2 commitments"],
        ["iso", "ISO 27001 / 27701"],
        ["cmmc", "CMMC level (defense contractor)"],
        ["nist", "NIST 800-171 / 800-53"],
        ["ferpa", "FERPA (education)"],
        ["glba", "GLBA (financial)"],
        ["gdpr", "GDPR / CCPA (consumer data)"],
        ["state_privacy", "State privacy (NY SHIELD, VCDPA, CPRA)"],
        ["industry", "Industry-specific (FDA 21 CFR 11, DEA EPCS)"],
        ["everify", "E-Verify / I-9 digital storage"],
        ["union", "Union / CBA labor requirements"],
        ["audio_consent", "Video audio two-party consent"],
        ["recording_retention", "Retention policies for recordings"],
        ["chain_custody", "Chain of custody for evidence export"],
        ["audit_log", "Required audit log retention duration"],
        ["encryption", "Required encryption at rest / in transit"],
        ["itar", "Export control / ITAR concerns"],
      ].map(([key, label]) => yn(key, label, undefined, { photo: "none" })),
    },
  ],
};

const photos: SectionDef = {
  key: "photos",
  number: 24,
  title: "Required photos",
  short: "Photos",
  icon: "camera",
  intro:
    "At least one photo per shot. For wide spaces take overlapping shots. Photos taken anywhere else in the walk can also be linked from the gallery.",
  blocks: [
    {
      kind: "fields",
      fields: [
        shot("exterior", "Site exterior — street view with address visible"),
        shot("entrances", "Building entrance (primary and secondary)"),
        shot("dock", "Loading dock / shipping door"),
        shot("roof", "Rooftop penetrations (if accessible)"),
        shot("lobby", "Reception / lobby wide shot"),
        shot("mdf_front", "MDF — rack front"),
        shot("mdf_back", "MDF — rack back (cables visible)"),
        shot("mdf_overhead", "MDF — overhead cabling / tray"),
        shot("mdf_floor", "MDF — floor / underfloor"),
        shot("mdf_power", "MDF — power circuits / breaker panel"),
        shot("mdf_ups", "MDF — UPS front panel + rear"),
        shot("mdf_hvac", "MDF — HVAC source / portable AC"),
        shot("mdf_door", "MDF — door and lock type"),
        shot("mdf_temp", "MDF — temp/humidity readout"),
        shot("mdf_labels", "MDF — labeling close-up (patch panel + jacks)"),
        shot("idfs", "Each IDF — front, back, pathway back to MDF"),
        shot("ceiling_tile", "Ceiling tile pulled above sample area (per space)"),
        shot("pathway", "Pathway above drop ceiling (tray / J-hooks)"),
        shot("riser", "Any firestopped riser or sleeve"),
        shot("hazard", "Hazard areas (asbestos warning, water, electrical)"),
        shot("fw_front", "Firewall front (serial visible)"),
        shot("fw_back", "Firewall back (cabling)"),
        shot("core_stack", "Core switch stack"),
        shot("closet_labels", "Each wiring closet patch panel labeling close-up"),
        shot("servers", "Each server — front and back"),
        shot("workstation_personas", "Each unique workstation setup (one per persona)"),
        shot("printers", "Each printer / MFP front with serial + model"),
        shot("conf_rooms", "Each conference room from both corners"),
        shot("nvr", "Camera NVR / recorder"),
        shot("alarm_panel", "Alarm panel face + cellular communicator"),
        shot("ac_panel", "Access control panel + wiring termination"),
        shot("ext_cameras", "Each exterior camera + mount"),
        shot("ext_doors", "Each exterior door with reader + strike / maglock"),
        shot("damage", "Pre-existing damage, scratches, water staining"),
        shot("demarc", "Demarc / telco MPOE room"),
        shot("generator", "Generator / ATS"),
        shot("specialty", "Specialty systems noted under Low-volt"),
      ],
    },
  ],
};

const risks: SectionDef = {
  key: "risks",
  number: 25,
  title: "Risks & blockers",
  short: "Risks",
  icon: "alert",
  intro: "Risks, blockers and open items surfaced during the walk.",
  blocks: [
    {
      kind: "table",
      table: {
        key: "risks",
        title: "Risks",
        singular: "Risk",
        columns: [
          q("risk", "Risk / blocker / observation", "textarea"),
          txt("area", "Area / section"),
          pick("level", "Risk level", RISK),
          txt("owner", "Owner"),
          q("needed_by", "Needed by", "date"),
          q("surfaced", "Date surfaced", "date"),
          notesCol,
        ],
        titleKeys: ["risk"],
        subtitleKeys: ["level", "owner"],
      },
    },
  ],
};

const rollup: SectionDef = {
  key: "rollup",
  number: 26,
  title: "Scope & budget rollup",
  short: "Rollup",
  icon: "calculator",
  intro:
    "Totals for the install team's BOM, labor estimate and phasing plan. Where a count can be derived from records you've captured, tap the suggestion to use it.",
  blocks: [
    {
      kind: "fields",
      title: "Scope counts",
      fields: [
        num("data_drops", "Total data drops needed", undefined, { extras: ["priority"] }),
        num("voice_drops", "Total voice drops (if separate)", undefined, { extras: ["priority"] }),
        num("ap_drops", "Total AP drops / PoE", undefined, { extras: ["priority"], suggest: { tables: ["aps"], label: "APs recorded" } }),
        num("camera_drops", "Total camera drops", undefined, { extras: ["priority"], suggest: { tables: ["cameras"], label: "cameras recorded" } }),
        num("ac_drops", "Total access-control drops", undefined, { extras: ["priority"], suggest: { tables: ["doors"], label: "doors recorded" } }),
        num("lv_drops", "Total specialty low-volt drops", undefined, { extras: ["priority"] }),
        num("switches_access", "Switches to deploy (access)", undefined, { extras: ["priority"], suggest: { tables: ["access_switches"], filterKeepReplace: ["Replace"], label: "switches marked Replace" } }),
        num("switches_core", "Switches to deploy (core / distribution)", undefined, { extras: ["priority"] }),
        num("aps", "APs to deploy", undefined, { extras: ["priority"], suggest: { tables: ["aps"], filterKeepReplace: ["Replace"], label: "APs marked Replace" } }),
        num("cameras", "Cameras to deploy", undefined, { extras: ["priority"], suggest: { tables: ["cameras"], filterKeepReplace: ["Replace"], label: "cameras marked Replace" } }),
        num("doors", "Access-control doors", undefined, { extras: ["priority"], suggest: { tables: ["doors"], label: "doors recorded" } }),
        num("workstations", "Workstations to deploy / re-image", undefined, { extras: ["priority"], suggest: { tables: ["workstations"], label: "seats recorded" } }),
        num("monitors_docks", "Monitors + docks", undefined, { extras: ["priority"] }),
        num("printers", "Printers / MFPs", undefined, { extras: ["priority"], suggest: { tables: ["printers"], filterKeepReplace: ["Replace"], label: "printers marked Replace" } }),
        num("handsets", "VoIP handsets", undefined, { extras: ["priority"] }),
        num("conf_rooms", "Conference rooms to equip", undefined, { extras: ["priority"], suggest: { tables: ["rooms"], label: "rooms recorded" } }),
        num("servers_ups", "Servers / UPS / rack units", undefined, { extras: ["priority"] }),
        num("cable_ft", "Rough linear feet of new cable", undefined, { unit: "ft", extras: ["priority"] }),
        num("tray_ft", "Rough linear feet of new tray / pathway", undefined, { unit: "ft", extras: ["priority"] }),
        num("fiber_pairs", "Fiber uplink pairs", undefined, { extras: ["priority"] }),
        num("firestops", "Firestop penetrations", undefined, { extras: ["priority"] }),
        num("core_drills", "Core drills (floor / wall)", undefined, { extras: ["priority"] }),
        num("after_hours_hrs", "After-hours labor hours estimated", undefined, { unit: "hrs", extras: ["priority"] }),
        num("lifts", "Lift / scissor / man-lift rentals", undefined, { extras: ["priority"] }),
        txt("hazmat", "Hazmat / abatement contingency", undefined, { extras: ["priority"] }),
        txt("ewaste", "Decommission / e-waste pickup", undefined, { extras: ["priority"] }),
      ],
    },
    {
      kind: "fields",
      title: "Recommended phasing",
      fields: [
        ["prep", "Pre-cutover prep", "Credentials, LOAs, carrier orders, licensing"],
        ["cabling", "Cabling / pathway (overnight / weekend)"],
        ["mdf", "MDF rebuild — core, firewall, UPS"],
        ["idf", "IDF closets"],
        ["access", "Access layer + wireless"],
        ["servers", "Server / storage migration"],
        ["workstations", "Workstation rollout (persona waves)"],
        ["printers", "Printer / MFP cutover"],
        ["phones", "Phone cutover / number port"],
        ["security", "Physical security — cameras / access"],
        ["decom", "Decommission / e-waste"],
        ["punch", "Punch list / training / documentation hand-off"],
      ].map(([key, label, hint]) =>
        txt(`phase_${key}`, label, hint, {
          placeholder: "Target window",
          extras: ["dependencies", "risk"],
          photo: "none",
        }),
      ),
    },
  ],
};

const SIGNOFF_STATUS = ["Done", "Not done", "Follow-up"];

const signoff: SectionDef = {
  key: "signoff",
  number: 27,
  title: "Sign-off",
  short: "Sign-off",
  icon: "pen",
  intro:
    "Confirm every section is populated, every required photo was captured, and both the walker and client POC agree on the scope flags.",
  blocks: [
    {
      kind: "fields",
      title: "Completion checklist",
      fields: [
        ["all_tabs", "All sections populated (N/A where not applicable)"],
        ["all_photos", "All required photos captured"],
        ["risks_reviewed", "Risks & blockers reviewed with client"],
        ["rollup_reviewed", "Scope & budget rollup reviewed with client"],
        ["owners", "Open items assigned to owners"],
        ["followup", "Follow-up walk required (specify in notes)"],
        ["credentials", "Credentials collected (admin, carrier, platform)"],
        ["nda", "NDA / MSA in place"],
        ["drawings", "Site drawings / floor plans obtained"],
        ["permits", "Permit / landlord approvals initiated"],
      ].map(([key, label]) => ({ ...pick(key, label, SIGNOFF_STATUS), photo: "none" as const })),
    },
    {
      kind: "fields",
      title: "Signatures",
      fields: [
        q("walker_sig", "Lead walker", "signature", { photo: "none" }),
        q("secondary_sig", "Secondary walker", "signature", { photo: "none" }),
        q("client_sig", "Client POC", "signature", { photo: "none" }),
      ],
    },
  ],
};

export const PRE_INSTALL_TEMPLATE: TemplateDef = {
  key: "pre_install_v1",
  title: "Pre-install site discovery",
  description:
    "Full infrastructure walk before a rip-and-replace: pathways, MDF/IDFs, network, endpoints, servers, physical security, compliance, scope rollup and sign-off.",
  sections: [
    cover,
    facility,
    mdf,
    idf,
    wan,
    firewall,
    switches,
    wireless,
    cabling,
    workstations,
    printers,
    voice,
    av,
    servers,
    storage,
    identity,
    apps,
    access,
    alarms,
    cameras,
    environmental,
    lowvolt,
    headcount,
    compliance,
    photos,
    risks,
    rollup,
    signoff,
  ],
};

export type { TableDef };
