import {
  AlertTriangle,
  AppWindow,
  Building2,
  Cable,
  Calculator,
  Camera,
  Cctv,
  Database,
  DoorClosed,
  Flame,
  Globe,
  HardDrive,
  KeyRound,
  Laptop,
  Layers,
  Monitor,
  Network,
  PenLine,
  Phone,
  Printer,
  Scale,
  Server,
  Shield,
  Siren,
  ToggleRight,
  Users,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  building: Building2,
  layers: Layers,
  server: Server,
  network: Network,
  globe: Globe,
  shield: Shield,
  toggle: ToggleRight,
  wifi: Wifi,
  cable: Cable,
  laptop: Laptop,
  printer: Printer,
  phone: Phone,
  monitor: Monitor,
  database: Database,
  "hard-drive": HardDrive,
  key: KeyRound,
  app: AppWindow,
  door: DoorClosed,
  siren: Siren,
  cctv: Cctv,
  flame: Flame,
  zap: Zap,
  users: Users,
  scale: Scale,
  camera: Camera,
  alert: AlertTriangle,
  calculator: Calculator,
  pen: PenLine,
};

export function SectionIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? Layers;
  return <Icon className={className} />;
}
